Platform/ARM: Fix FVP broken build with "-D DT_SUPPORT"
The UEFI build fails for ArmVExpress-FVP-AArch64 when using the
"-D DT_SUPPORT" buildoption.

ArmVExpressDtPlatformDtbLoaderLib is missing the ArmVExpressPkg.dec package
and fails with:
.../Platform/ARM/VExpressPkg/Include/Platform/RTSM/ArmPlatform.h:19:33:
fatal error: VExpressMotherBoard.h: No such file or directory

Cc: Leif Lindholm <leif.lindholm@linaro.org>
Cc: Ard Biesheuvel <ard.biesheuvel@linaro.org>
Contributed-under: TianoCore Contribution Agreement 1.1
Signed-off-by: Andrew Turner <andrew@fubar.geek.nz>
Tested-by: Thomas Abraham <thomas.abraham@arm.com>
Reviewed-by: Leif Lindholm <leif.lindholm@linaro.org>